import "./globals.css";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";
import { Manrope, Playfair_Display, Poppins } from "next/font/google";

const manrope = Manrope({ subsets: ["latin"], variable: "--font-manrope" });
const playfair = Playfair_Display({ subsets: ["latin"], variable: "--font-playfair" });
const poppins = Poppins({ subsets: ["latin"], variable: "--font-poppins", weight: "400" });

export const metadata: Metadata = {
    title: "Daily Routine",
    description: "Generated by Daily Routine",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className={cn("relative min-h-dvh px-4! py-6! antialiased", manrope.variable, playfair.variable, poppins.variable)}>
                {children}
                <Toaster position="top-center" toastOptions={{ classNames: { description: "!text-current !opacity-100" } }} />
            </body>
        </html>
    );
}
